version: 2.1

orbs:
  golang: circleci/go@1.11.0

executors:
  machine-medium:
    machine:
      image: ubuntu-2204:2023.04.2
      docker_layer_caching: true
    working_directory: ~/repo
    resource_class: medium

jobs:
  test-and-build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - golang/install:
          cache: true
          version: 1.22.1
      - run:
          name: Run Tests
          command: |
            go run github.com/onsi/ginkgo/v2/ginkgo -r lib/
      - run:
          name: Build
          command: |
            go build

workflows:
  go-deploy:
    jobs:
      - test-and-build

