version: 2.1

orbs:
  golang: circleci/go@1.11.0

jobs:
  test-and-build:
    docker:
      - image: cimg/base:current
    steps:
      - golang/install:
          cache: true
          version: 1.22.1
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Run Tests
          command: |
            go run github.com/onsi/ginkgo/ginkgo -r lib/
      - run:
          name: Build
          command: |
            go build

workflows:
  go-deploy:
    jobs:
      - test-and-build

